"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const templateEmail_controller_1 = require("../controllers/templateEmail.controller");
const router = (0, express_1.Router)();
router.get("/", templateEmail_controller_1.getAllTemplates);
router.get("/:type", templateEmail_controller_1.getTemplateByType);
router.post("/", templateEmail_controller_1.createTemplate);
router.put("/:id", templateEmail_controller_1.updateTemplate);
router.delete("/:id", templateEmail_controller_1.deleteTemplate);
exports.default = router;
